[netty]: Trying to load the native epoll lib. Currently failing with:
15:40:16,264 ERROR [stderr] (ServerService Thread Pool -- 84) java.lang.NoClassDefFoundError: io/netty/channel/epoll/NativeStaticallyReferencedJniMethods
15:40:16,269 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
15:40:16,270 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
15:40:16,271 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
15:40:16,271 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
15:40:16,272 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
15:40:16,272 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.lang.Runtime.load0(Runtime.java:768)
15:40:16,272 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.lang.System.load(System.java:1837)
15:40:16,273 ERROR [stderr] (ServerService Thread Pool -- 84)   at io.netty.netty-common@4.1.70.Final//io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
15:40:16,273 ERROR [stderr] (ServerService Thread Pool -- 84)   at io.netty.netty-common@4.1.70.Final//io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:301)
15:40:16,274 ERROR [stderr] (ServerService Thread Pool -- 84)   at io.netty.netty-common@4.1.70.Final//io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:202)
15:40:16,274 ERROR [stderr] (ServerService Thread Pool -- 84)   at io.netty.netty-transport-native-epoll@4.1.70.Final//io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:306)
15:40:16,274 ERROR [stderr] (ServerService Thread Pool -- 84)   at io.netty.netty-transport-native-epoll@4.1.70.Final//io.netty.channel.epoll.Native.<clinit>(Native.java:85)
15:40:16,279 ERROR [stderr] (ServerService Thread Pool -- 84)   at io.netty.netty-transport-native-epoll@4.1.70.Final//io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40)
15:40:16,280 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.apache.activemq.artemis@2.19.0//org.apache.activemq.artemis.core.remoting.impl.netty.CheckDependencies.isEpollAvailable(CheckDependencies.java:36)
15:40:16,280 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.apache.activemq.artemis@2.19.0//org.apache.activemq.artemis.core.remoting.impl.netty.NettyAcceptor.start(NettyAcceptor.java:414)
15:40:16,281 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.apache.activemq.artemis@2.19.0//org.apache.activemq.artemis.core.remoting.server.impl.RemotingServiceImpl.startAcceptors(RemotingServiceImpl.java:318)
15:40:16,281 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.apache.activemq.artemis@2.19.0//org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.completeActivation(ActiveMQServerImpl.java:3363)
15:40:16,285 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.apache.activemq.artemis@2.19.0//org.apache.activemq.artemis.core.server.impl.LiveOnlyActivation.run(LiveOnlyActivation.java:78)
15:40:16,286 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.apache.activemq.artemis@2.19.0//org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.internalStart(ActiveMQServerImpl.java:655)
15:40:16,286 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.apache.activemq.artemis@2.19.0//org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.start(ActiveMQServerImpl.java:568)
15:40:16,289 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.apache.activemq.artemis@2.19.0//org.apache.activemq.artemis.jms.server.impl.JMSServerManagerImpl.start(JMSServerManagerImpl.java:374)
15:40:16,291 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.wildfly.extension.messaging-activemq//org.wildfly.extension.messaging.activemq.jms.JMSService.doStart(JMSService.java:210)
15:40:16,308 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.wildfly.extension.messaging-activemq//org.wildfly.extension.messaging.activemq.jms.JMSService.access$000(JMSService.java:65)
15:40:16,310 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.wildfly.extension.messaging-activemq//org.wildfly.extension.messaging.activemq.jms.JMSService$1.run(JMSService.java:100)
15:40:16,311 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
15:40:16,312 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
15:40:16,312 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
15:40:16,312 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
15:40:16,313 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
15:40:16,313 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
15:40:16,316 ERROR [stderr] (ServerService Thread Pool -- 84)   at java.base/java.lang.Thread.run(Thread.java:829)
15:40:16,316 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
15:40:16,317 ERROR [stderr] (ServerService Thread Pool -- 84) Caused by: java.lang.ClassNotFoundException: io.netty.channel.epoll.NativeStaticallyReferencedJniMethods from [Module "io.netty.netty-common" version 4.1.70.Final from local module loader @353352b6 (finder: local module finder @4681c175 (roots: /home/ehsavoie/dev/wildfly/wildfly/build/target/wildfly-26.0.0.Beta1-SNAPSHOT/modules,/home/ehsavoie/dev/wildfly/wildfly/build/target/wildfly-26.0.0.Beta1-SNAPSHOT/modules/system/layers/base))]
15:40:16,318 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
15:40:16,318 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
15:40:16,320 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
15:40:16,321 ERROR [stderr] (ServerService Thread Pool -- 84)   at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
15:40:16,321 ERROR [stderr] (ServerService Thread Pool -- 84)   ... 32 more